<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <Authors>Cebrail Kara</Authors>
    <Company>SafirSuite</Company>
    <Product>SafirGuard Security Suite</Product>
    <Copyright>Copyright © 2026 Cebrail Kara (SafirSuite)</Copyright>
    <Description>SafirGuard Desktop Security Suite - Advanced AI Cyber Defense &amp; Antivirus</Description>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="8.0.11" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2903.40" />
    <EmbeddedResource Include="wwwroot\**\*" />
  </ItemGroup>

</Project>
